FlipSideHR/FlyptoX

README.md
_CONTRIBUTING.md
_PRESS-RELEASE.md
_STYLE-GUIDE.md

Copied over thesis project markdown files from Hack Reactor's skeleton thesis project repo.

Add thesis project markdown files

---

.gitignore
Gruntfile.js
app/app.html
app/app.js
app/app.less
app/app_test.js
app/modules.js
bower.json
db/migrations/add-users.js
db/seeds/seed-users.js
knexfile.js
package.json
server/main.js
server/models/User.js
server/views/index.html
test/karma.conf.js

Used this generator for AngularJS + Express + PostgreSQL: https://www.npmjs.com/package/generator-angular-express.
Added .gitignore file.
Take a look and see if this is the structure that we want. :smiley:

Generate PEAN stack app structure with Yeoman

---

server/controllers/users.js
server/main.js
server/routes/api.js

Setting up the basic server routes and controllers structure that has worked well in previous projects.
You will not that modules are added to the `global` scope in `main.js` which makes them accessible from other code modules on the server.

setup routes and controllers directory structure

---

README.md

Nothing major here. I noticed these entries in the README needed updating while I was catching up with project status. 
- made the roadmap link to issues correctly
- updated tech stack versioning numbers.

Updated README.md with working roadmap link and tech stack versioning.

---

app/app.html
app/app.less
app/lib/services/account.services.js
app/modules.js

Build out order execution UI and data model.

---

Gruntfile.js
bower.json
client/app/app.html
client/app/modules.js
server/controllers/users.js
server/main.js
server/models/User.js
server/temp/angular__auth.js
server/views/index.html

Work on resolving syntax and Angular errors

---

Gruntfile.js
db/migrations/20150714120729_add_users.js
server/models/User.js
test/server/models/helpers.js
test/server/models/user.model.spec.js

I added some tests to the user model.
I also added some different ways to run grunt tests:
- `grunt test:models` runs just model tests
- ` grunt test:controllers` runs just controller tests
- `grunt test:server` still runs all server tests

Updated user model tests and grunt test commands

---

db/migrations/20150714121033_add_orders.js
db/migrations/20150714121034_add_trades.js
db/migrations/20150714121035_add_transactions.js
server/controllers/book.js
server/controllers/users.js
server/main.js
server/models/Transaction.js
server/routes/api.js
server/utils/bookshelf.js
server/utils/models.js
test/server/controllers/users.controller.spec.js
test/server/models/helpers.js
test/server/models/order.model.spec.js
test/server/models/trade.model.spec.js
test/server/models/user.model.spec.js

- Updated database schema and relevant files d11ca529513bbf4f79e75c822e5694084e747b60
- OrderBook queries (read only)
- Reverting back to use process.env.NODE_ENV to configure knex, it is much cleaner approach.
The default environment is `development` so run knex migrations and seeding on test database (flyptox_test)
`knex --env test migrate:latest`
`knex --env test seed:run`
To run the server unit tests on the test db:
`NODE_ENV=test grunt test:server`

order book queries for levels 1, 2 and 3

---

client/app/app.html
server/views/index.html

We'll deal with LESS compilation later.

Temporarily move css into html

---

server/controllers/book.js
server/controllers/users.js
server/models/Account.js
server/models/Currency.js
server/models/CurrencyPair.js
server/models/Order.js
server/models/Trade.js
server/models/Transaction.js
server/models/User.js
server/utils/bookshelf.js
server/utils/models.js
test/server/controllers/book.order.aggregation.spec.js
test/server/controllers/users.controller.spec.js
test/server/models/helpers.js
test/server/models/model.relations.spec.js
test/server/models/order.model.spec.js
test/server/models/trade.model.spec.js
test/server/models/user.model.spec.js

- Reverted to old way of loading models, to fix issue with relations.
- Updated tests.
- All server unit tests passing.
- Ready to merge.

reverted to old model setup

---

server/routes/api.js

Quick Fix.. reference to the models from API router

fixed model references in api router

---

.travis.yml
knexfile.js
package.json
test/server/controllers/book.order.aggregation.spec.js

This adds travis continuous integration.

Integrating travis-ci

---

.travis.yml
Gruntfile.js
knexfile.js
package.json
server/test/controllers/book.order.aggregation.spec.js
server/test/controllers/users.controller.spec.js
server/test/models/helpers.js
server/test/models/model.relations.spec.js
server/test/models/order.model.spec.js
server/test/models/trade.model.spec.js
server/test/models/user.model.spec.js
test/server/controllers/book.order.aggregation.spec.js

Curious if this makes more sense for testing:
- This PR moves the server test directory into the server directory. 
- This way test modules do not need to do so much cross directory referencing to load models.
- (this pr also includes the travis-ci updates)

Move test directory for cleaner structure.

---

server/utils/recreateDB.js

Verified the script now works as expects on both DBs.
Thank you for finding this Mokhtar!

Fixed issue where DB creation script was not running migrations on dev

---

db/migrations/20150714120729_add_users.js
db/migrations/20150714121032_add_accounts.js
db/migrations/20150714121033_add_orders.js
db/migrations/20150714121034_add_trades.js
db/migrations/20150714121035_add_transactions.js
server/models/Account.js
server/models/Order.js
server/models/Trade.js
server/models/Transaction.js
server/models/User.js
server/routes/api.js
server/test/helpers.js
server/test/models/trade.model.spec.js
server/test/models/user.model.spec.js

- Updated DB schema to use timestamps
- Added a currency_pair_id column to trades table for quick lookup by currency pair
- added `/api/v1/products/:id/ticker` api endpoint to get the latest trade (market price)

update database schema to use timestamp (created_at, updated_at)

---

.jshintrc
Gulpfile.js
client/app/app.html
server/controllers/book.js
server/controllers/tokens.js
server/main.js
server/models/Account.js
server/models/Currency.js
server/models/CurrencyPair.js
server/models/Order.js
server/models/Trade.js
server/models/Transaction.js
server/models/User.js
server/routes/api.js
server/routes/auth.js
server/test/controllers/book.order.aggregation.spec.js
server/test/controllers/users.controller.spec.js
server/test/models/order.model.spec.js
server/test/models/trade.model.spec.js
server/test/models/user.model.spec.js
server/utils/recreateDB.js

This resolves all jshint linting complaints on the server side. 
Feel free to review/consider/user/reject. 
~~Its just a quick way to shut off the linter.~~ I realized after PRing this that it also has some model updates attached to it. Oops!
Still mostly nothing done here that cant be easily undone when needed I think.
- Orders.js and orders.spec.js both have some minor updates.
- All the other files represent minor changes to quiet the linter.

Jshint (server) fixes

---

Gulpfile.js

No idea why this works. Or why it stopped working in the previous method.

Resolved issue with browser-sync not injecting client side data

---

docs/api/README.md
server/controllers/tokens.js
server/controllers/users.js
server/models/User.js
server/routes/auth.js
server/test/controllers/users.controller.spec.js

- auth api methods return error messages with http error status codes to display to user in UI.
- updated `/api/auth/whoami` route to handle GET request (POST or UPDATE can be used for updating information in future)
- started API docs
this is taking too long to write in detail I will add more comments before each API route if required

refactored auth api methods

---

server/controllers/book.js

handle case when order book might be empty

handle null order

---

docs/api/README.md

thought I included this in last PR.. 
just markdown fixed for api docs readme

fixed table formatting

---

package.json
server/main.js
server/routes/api.js

tried to better document the api
added some additional error checking 
I'm including two additional node modules: morgan and debug it might be one of these is causing travis to fail the build?

updated api docs

---

Gulpfile.js
bower.json
client/app/components/orderbook/orderbook.js
package.json
server/views/index.html

Bower and npm installed socket.io, then added bower file to Gulpfile for minification.
Wrote socket.on functionality in orderbook for creating and remove an order.

Set up socket.io for orderbook

---

client/app/components/orderbook/orderbook.html
client/app/components/orderbook/orderbook.js

Changed order of bids and asks, removed need to reverse and fixed an error around data binding.

Minor fixes to order book.

---

server/controllers/web-market-streamer.js
server/main.js

Simon, Amy and Dick already have this on their local branches.
This is probably just for you Michael

fixed socket.io setup to work with express

---

client/app/components/orderbook/orderbook.html
client/app/components/orderbook/orderbook.scss

Additional prettifying.

---

client/app/components/orderbook/orderbook.html
client/app/components/orderbook/orderbook.scss

CSS for .bid-price isn't rendering for some reason.
Cool button effect.

Clean up styling in orderbook

---

client/app/app.html
client/app/app.scss
client/app/components/auth/auth.scss
client/app/components/auth/login.html
client/app/components/auth/signup.html
client/app/components/orderbook/orderbook.scss
client/app/landing.html

Some basic styling edits done on landing/auth pages.
Added form tags to login/sign up and removed text-decoration on links. Altered input placeholders and removed h3 tags.

Small CSS edits to landing and auth pages

---

client/app/components/orderbook/orderbook.html
client/app/components/orderbook/orderbook.js

- You see your own orders on the orderbook page now.
- You can click a button to cancel a particular ordering. The orderbook display and the list of your orders update as expected (the order is removed).
- Totally unstyled, breaks the display of the page a bit. CSS for these changes coming up next.
Merge if you don't mind a janky looking orderbook page for a while, wait until the css comes through if we only want to merge it when it has at least a bit of polish.

Show users' orders on the orderbook page. Can cancel them as well.

---

client/app/components/orderbook/orderbook.html
client/app/components/orderbook/orderbook.js
client/app/components/orderbook/orderbook.scss

- The orderbook entry form and the listing of a user's orders have some styling now. They won't break the page layout.

Repositioning and styling of orderbook entry form and myOrders list.

---

client/app/app.scss
client/app/components/auth/auth.scss

The sign up and login pages look cleaner!

Add clean styles to login/sign up forms

---

client/app/components/orderbook/orderbook.js
server/models/Order.js
server/routes/api.js

Tests are passing. Im able to use the client as expected. Please test to your hearts content..

Moves the orderToJSON function to a method on the order object.

---

client/app/components/orderbook/orderbook.scss

Adjust margin-right CSS property for the orderbook's right-hand column.

---

client/app/components/orderbook/orderbook.html

Fix: Users can now enter fractional prices / sizes on the order entry form.

---

client/app/app.html
client/app/app.js
client/app/app.scss

Add a live trade ticker to the navbar.

---

client/app/app.html
client/app/app.scss
client/app/components/orderbook/orderbook.html
client/app/components/orderbook/orderbook.scss
client/app/landing.html
server/views/index.html

Clean up app design

---

db/migrations/20150714121032_add_accounts.js
db/migrations/20150714121035_add_transactions.js
server/controllers/users.js
server/marketEngine/accountManager.js
server/marketEngine/matcher.js
server/marketEngine/orderDesk.js
server/routes/api.js
server/routes/auth.js
server/test/controllers/users.controller.spec.js
server/test/marketEngine/accountManager.spec.js
server/test/marketEngine/orderDesk.spec.js

- updated db schema to have a credit and debit fields in transactions table (run recreateDB -dev)
- new users get some funds in their USD and BTC accounts for testing (account opening transaction)
- Implemented methods to check account balance (derived from transaction history on an account)
- implemented method to calculate current holds on an account (derived from open limit orders)
- available balance = account balance - holds

Accounting

---

server/controllers/users.js
server/routes/auth.js
server/test/controllers/users.controller.spec.js
server/test/marketEngine/orderDesk.spec.js

Making users.signup reusable for use in orderdesk unit test. if https://github.com/FlipSideHR/FlyptoX/pull/135 is merged it will not be enough to just have a user account, to test orders and order matching.

updates to users controller

---

Gulpfile.js
server/test/controllers/book.order.aggregation.spec.js
utils/dbTools.js

you can also use --spec on any gulp command related to testing
(including  the default gulp command) to get spec reporting instead of
nyan.

Updated gulpfile to build assets out and to delete test db before testing.

---

client/app/components/account/account.controller.js
client/app/components/account/account.html
client/app/components/account/account.scss

Layout-focused CSS changes for the account page. Order / trade history proof of concept.

---

README.md

Corrected spelling and added some new/more relevant info.

Fix spelling error in bold at top of readme.

---

client/app/components/account/account.controller.js
client/app/components/account/account.html
client/app/components/chart/chart.controller.js
server/routes/api.js

- Fixed the 'ledger' endpoint for the accounts API.
- Connected the history view on the account management page with the transactions API. Users can now see a history of their transaction records.

Add a transaction view to the account mgmt page. Fix for an accounts API.

---

client/app/app.scss
client/app/components/orderbook/orderbook.html
client/app/components/orderbook/orderbook.scss

Hey guys - just thought Id throw my hat in the ring on the orderbook layout thing. 
I know (first hand) what a pain this stuff is... but I think I have this part working ok....
Check it out: 
Big:
Scrunched:
This is still not great because it is a fixed height, however it does seem to be usable in multiple resolutions, and keeps the center bar of the book in the center.

A meager attempt at getting the order box laid out better.

---

server/routes/api.js

This should fix the incorrect available balance returned by the accounts api

fix api call to get account balances

---

server/routes/api.js

This was causing a problem on the server, but worked fine locally.

Added promise requirement to api.js

---

client/app/components/orderbook/orderbook.html
client/app/components/orderbook/orderbook.scss
client/app/lib/auth.service.js

Miscellaneous orderbook fixes.

---

client/app/lib/auth.service.js

Logout was throwing an error and not returning to the landing page. No more errors. Properly returns user to landing page after logging out.

Fixed the logout behavior.

---

client/app/app.scss
client/app/landing.html

Some css got chopped earlier I think and some stuff wasnt displaying properly.
This patch fixes that. It also brings the cool icons and data points that simon made more into focus and adds some new data points. Please feel free to edit/add/change - whatever.

Fixed some missing css and expanded on landing page.

---

client/app/app.html
client/app/components/orderbook/orderbook.html

Behold:
The account page is still not done:

Formatted numbers on the orderbook page and the ticker as currencies.

---

client/app/app.scss
client/app/components/auth/auth.scss
client/app/landing.html

Aligned the svgs and nav ticker. Adjusted height of sections so text isn't cut off.
Is it just me or is the documentation button not centered?

Clean up site design

---

flyptox

The setup script had the appearance of being frozen because it didnt give any output until it was finished. Now it gives realtime output and feels a little nicer/better.

Updated setup script to be more verbose realtime.

---

client/app/components/orderbook/orderbook.html
client/app/components/orderbook/orderbook.scss

Fix miscellaneous formatting issues on the orderbook page.

---

flyptox
server/marketEngine/accountManager.js

- Went ahead and finished a couple of these anyway. 
- This CLI has a lot of options available (like running as as an ssh server, or providing a repl to the DB, or to node..)
- This exposes limited functionality. Currently you can:
- use help to get info about available commands
- get a list of users
- get info about a specific user by email
- make deposits/withdrawals to a user account
- To use run `./flyptox` (should already have run setup, or jsut be setup)
- Some available commands are:
- `users list`
- `users get <email>`
- `users --currency <type> --deposit <amount> <email>`
- example: `users --currency USD --deposit 10000 me@myemail.com`
- You can also use short switches:
- `-c` or `--currency`
- `-d` or `--deposit`
- `-w` or `--withdraw`
- Currency can be set to BTC or USD …

Some basic CLI Admin tools

---

client/app/components/account/account.scss
client/app/components/auth/auth.scss

Account page CSS

---

flyptox

This is a change to the flyptox setup script that provides more verbose output. 
I had these changes merged already, but I accidentally sent a new PR which overwrote them... oops!

Re-added some changes that accidentally got dropped (by me).

---

client/app/components/account/account.controller.js
client/app/components/account/account.html
client/app/components/account/account.scss

Add a basic form to the settings section of the accounts page.

---

client/app/landing.html

just some rewording.. one or two typos

some edits on the landing page

---

client/app/components/orderbook/orderbook.html

Moved side button on order entry form.

---

client/app/components/account/account.html
client/app/components/account/account.scss

Add style to account settings form
