- README.md
- knexfile.js
I suggest we use a common role (username) for knex configuration.
To create a flyptox user in postgres run the following command in `psql` 
create role flyptox with login;
grant all privileges on database flyptox to flyptox;
> use common pg role name 'flyptox' for development

- .bowerrc
bower components will be installed into  `client/bower_components` instead of the root directory
> added .bowerrc

- server/models/User.js
- server/utils/bookshelf.js
- test/server/models/helpers.js
- test/server/models/order.model.spec.js
- test/server/models/trade.model.spec.js
- test/server/models/user.model.spec.js
- This PR properly introduces real test DB usage. 
- Now all tests just write to the db without trying to track it,
- tests can call utils.clean before/after/whenever to clean the db rows. 
- utils.clean currently only cleans trades, orders, users.
> Updated bookshelf export and test cleanup methods

- Gruntfile.js
- README.md
This PR just adds some instructions to the readme about using the testDB, and grunt test commands.
It also removes the need to prefix tests with NODE_ENV. Grunt takes care of this for us now.
> Updated readme with test/testdb info

- .gitignore
- .travis.yml
- README.md
- knexfile.js
- server/models/Order.js
- server/test/models/helpers.js
- server/test/models/order.model.spec.js
- server/utils/recreateDB.js
This PR introduces an update to the recreateDB script which now accepts option flags.
- `node server/utils/recreateDB`  drop, recreate, add privs, migrate and seed the **test** db.
- `node server/utils/recreateDB -dev` drop, recreate, add privs, migrate and seed the **dev** db.
- `node server/utils/recreateDB -travis` uses the knexfile travis config. 
Which brings us to the knexfile.
- The knexfile now has a travis setting which can be left alone
- The knexfile also has an admin setting which requires your postgres username and db (it signs in with these to manipulate the test and dev dbs.)
- TODO: So now that we can use this method to create the DB, the readme file needs to be updated with the correct (simpler) instructions.
I also added some new validations and tests on the orders …
> recreateDB script updated and minor model/test updates.

- .gitignore
- .travis.yml
- README.md
- knexfile.js
- server/models/Order.js
- server/test/controllers/users.controller.spec.js
- server/test/helpers.js
- server/test/models/helpers.js
- server/test/models/order.model.spec.js
- server/test/models/trade.model.spec.js
- server/test/models/user.model.spec.js
- server/utils/recreateDB.js
For your consideration:
This moves the test helpers file into the root test directory so that all files that need it can equally access it. it just makes more sense for it to go there
Its a tiny patch, but in order to hopefully keep from any major merge conflicts I wanted to get it out there quick. 
**(this patch also contains everything in the [recreateDB PR](https://github.com/FlipSideHR/FlyptoX/pull/50). Merging this includes those changes as well. )** I can separate out if needed.
> Test Helpers relocation

- Gulpfile.js
- README.md
- server/models/Order.js
This is basically what running `gulp` does except there is no browser-sync, no watching client-files, not even a server running. 
just run `gulp serverTestRunner` and gulp will watch all server files for changes, then lint and test (with nyan cat reporting)
> Implemented 'gulp serverTestRunner' which lints/tests server files on update.

- Gulpfile.js
- client/app/app.html
- server/main.js
- server/views/index.html
Ok, in the interest of faster builds, and less crud to suffer through, I removed minification from the default build path. 
Now gulp with just concat the JS and put it in dist.
To create a minified version use `gulp build-dist`. This currently will not be used by the application, but we will eventually make gulp smart enough to tell the index.html file whether to use minified js or regular js based on the environment its running in. For now not using minification keeps things simple, and fast for development.
> Added build path with no minification. (build path with minification remains)

- Gulpfile.js
- Now gulp by default will not minify js files.
- There is a gulp-dist command for building out the minified js
- This should improve a lot of wonkieness, and definitely the speed of builds.
- It will be trivial for someone to configure gulp to use minified files in production.
> Turned off js minification during development.

- Gulpfile.js
This PR also makes gulp 'put away its toys' by making sure that server:tests reset's the environment after they are done running; squashing a bug that could have the server write to test db when it should be writing to the dev db.
to get full 'spec' reporting just use `gulp test:server --reporter=spec`
> Put server tests into nyan-cat mode by default.

- Gulpfile.js
Since browser-sync's socket.io is conflicting with the applications, it has been turned off by default. 
In my **extremely limited** testing, I found that even though the browser was showing an error, both browser-sync and the application **appeared** to still be consuming and responding to socket data, so you can still use gulp with the switch `gulp --bs` to use browser sync if you find it useful and want to see if it works for you.
Otherwise just run `gulp` and connect to the server in your browser as normal (localhost:9999).
> Turned gulp browser-sync off by default.

- server/controllers/matcher.js
- server/controllers/web-market-streamer.js
Just attempting to keep a consistent data format of the models when being passed around in events.. with the data returned from api calls..  so data format coming down the pipe over socket.io and rest api calls is identical.. 
Need to redo this again later.. especially  to make sure date strings are always in ISO 8601 format.
Best place I think would be to override toJSON in the bookshelf  model definition.
I'll explore that and come back with a solution.
This PR however can me merged once reviewed.
> emit JSON in trade event, not a bookshelf model

- package.json
- server/controllers/app-events.js
- server/controllers/matcher.js
- server/test/controllers/matcher.spec.js
Replaced the builtin node EventEmitter with an async event emitter module:
https://www.npmjs.com/package/async-eventemitter
The order matcher now queues incoming orders to be processed in order. (We might need a way to persist the queue incase of server failure so it can pickup and continue processing on restart)
> async event emitter, and async queue for order matching

- server/routes/api.js
the server sends an empty array response instead of a 404
> Fixed issue with server sending 404 response to ticker api requests 

- client/app/app.html
- client/app/app.js
- client/app/app.scss
Couldn't capture a screenshot because it highlights for just about a second. Also, not sure if the color, effects, timing, etc. is final, I doubt it is. But this shows how to do live CSS updates based on events received from socket.io.
> Trade ticker now changes color based on whether the last trade was an up- or down-tick.

- Gulpfile.js
- client/app/app.html
- client/app/app.js
- client/app/components/account/account.controller.js
- client/app/components/account/account.html
- client/app/components/account/account.scss
- client/app/components/orderbook/orderbook.html
- Account management page layout. Work-in-process for now. Starting with being able to pull and filter various kinds of account history into a table (orders, trades, transactions to start with).
- Remove Chartist.js from dependencies.
- Switch price and size on the orderbook page.
- Fix ui-router to point to state 'account' as a child of state 'landing'.
> Account Management page + miscellaneous updates

- client/app/components/orderbook/orderbook.controller.js
- client/app/components/orderbook/orderbook.html
Rough cut in terms of how it was implemented...it is quite janky, if I do say so myself...but anyways:
- Unstyled div tags display the user's balance, followed by a slash, followed by available balance.
- Currently, showing two divs...one for USD, one for BTC. Imagine we have 20 currencies available though...which should be shown?
- You'll notice the balances don't ever update after orders are placed. They are being refreshed, but Mokhtar believes it is a bug with the API itself.
> Display user's account balances on the orderbook page.

- client/app/app.js
- client/app/components/auth/auth.controller.js
- client/app/lib/auth.service.js
This ensures that our auth token is only sent with request to /api.
Any $http requests with url starting with http or https could be potentially external api and we wouldn't want them to get our token..
Token will now be stored in sessionStorage instead of localStorage. data stored in sessionStorage will be destroyed when a tab is closed. If a new tab is opened it has it's own sessionStorage so user will require to login again.
> only send token with /api calls

- server/api/v1.js
- server/controllers/web-market-streamer.js
- server/marketEngine/matcher.js
- server/test/controllers/matcher.spec.js
a market order will only be filled up to maximum possible given a user's available funds
a market order will not execute if available balance equals zero
In the mean time I tested it. looks to be working.. try it out.. see if you can break it or find a problem with the code let me know.
streamer will not send new:order messages for market orders.
~~UI needs be updated not to add market orders to list of open orders~~ 
`/api/v1/orders` now only returns limit orders (it doesn't make sense to show market orders in the open orders list)
only limit orders can be cancelled, market orders will automatically complete once either the market is exhausted or the user's balance drops to zero
> market order - limit filling order relative to available funds

- client/app/app.js
- client/app/app.scss
- client/app/components/account/account.controller.js
- client/app/components/account/account.html
- client/app/components/account/account.scss
- client/app/components/orderbook/orderbook.controller.js
- client/app/components/orderbook/orderbook.html
- Add a neutral colored effect on the trade ticker in the case when the current trade executes at the same price as the previous price, a.k.a. an "equal-tick" (yes, I made that up).
- Remove currency formatting from the BTC figures on the orderbook page.
> BTC formatting, 'equaltick' effect on the ticker, wallet balances on the accounts page.

- client/app/components/account/account.scss
The two inline divs previously would separate into two rows when the window was too small. I've changed the display from inline-block to table-cell and tweaked the CSS slightly for spacing.
> Auto height for inline divs on account page
